name: Trigger web deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Trigger deployment
        run: curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/045f6503-e7e0-482b-acbe-637ce072aa66"